version: "3"
services:
  config-server-all:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/config-server-all-in-one:1.0.7
    build: .
    environment:
      MYSQL_HOST: mysql
      MONITOR_TYPE: rabbitmq
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "80:80"
  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"