version: "3"
services:
  config-server-all:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/config-server-all-in-one:1.0.5
    build: .
    environment:
      MYSQL_HOST: mysql
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"