= Spring Cloud 配置中心
:toc: left
:docinfo: shared
:docinfodir: ../css
:stylesheet: ../css/adoc-github.css
:nofooter:
:sectnums:
:docker-address: https://docs.docker.com
:gitee-address: https://gitee.com
:gitee-address-allinone: {gitee-address}/consolelog/docker-config-server-all-in-one
:gitee-address-backend: {gitee-address}/consolelog/codeforfun-config-server
:gitee-address-frontend: {gitee-address}/consolelog/codeforfun-config-server-frontend
:xingfa-address: http://xingfa.org/
:minfadian-address: https://paperclip.feishu.cn/file/boxcnZGTyENVDRcBIRUlFtM0YVf

== 快速开始

本项目最快的启动方式就是使用 {docker-address}[`docker`] 以及 `docker` 官方提供的 {docker-address}/compose/[`docker-compose`] 。

前往仓库 {gitee-address-allinone} 中下载 {gitee-address-allinone}/raw/master/docker-compose.yml[`docker-compose.yml`] 以及 {gitee-address-allinone}/raw/master/schema.sql[`schema.sql`] 两个文件

将这两个文件放到同一个目录中，并执行 `docker-compose up -d` 命令启动服务

启动后即可通过 http://localhost 地址访问并管理配置中心了

NOTE: 如果您熟悉Spring Cloud 以及 NodeJS ，也可以直接拉取本项目的前后端源代码来启动

// 功能介绍
include::feature.adoc[]

//附录
include::appendix.adoc[]

== 源码地址

源码托管在 {gitee-address}[Gitee] 中：

{gitee-address-frontend}[Gitee-配置中心-前端]、
{gitee-address-backend}[Gitee-配置中心-后端]、
{gitee-address-allinone}[Gitee配置中心-快速启动]

同时也提供了 https://github.com/[Github] 地址作为备用：

https://github.com/qq253498229/codeforfun-config-frontend[Github-配置中心-前端]、
https://github.com/qq253498229/codeforfun-config-server[Github-配置中心-后端]、
https://github.com/qq253498229/docker-config-server-all-in-one[Gitee配置中心-快速启动]

== 开源协议

本项目遵循 MIT 协议，虽然我也不知道这个协议具体是啥意思，但是原则上你可以随便使用本项目，当然前提是不触犯法律: {xingfa-address}[中华人民共和国刑法] 、 {minfadian-address}[中华人民共和国民法典(草案)]。

== 更新日志

懒得写了，以后再说吧

{gitee-address-backend}/commits/master[后端提交记录]

{gitee-address-frontend}/commits/master[前端提交记录]

[[contribution]]
== 贡献指南

你可以在 {gitee-address-frontend}/issues[前端] 、 {gitee-address-backend}/issues[后端] 以及 {gitee-address-allinone}/issues[快速启动] 的 issues 列表中提交 issue。

同时您也可以提供 PullRequest 贡献代码。