= Spring Cloud 配置中心
:toc: left
:docinfo: shared
:docinfodir: ../css
:stylesheet: ../css/adoc-github.css
:nofooter:

== 快速开始

本项目最快的启动方式就是使用 https://www.docker.com/[`docker`]，并且 `docker` 官方提供的 https://docs.docker.com/compose/[`docker-compose`] 更会简化部署流程。

=== 启动配置中心

使用本项目提供的 https://raw.githubusercontent.com/qq253498229/docker-config-server-all-in-one/master/docker-compose.yml[`docker-compose`](其中 https://raw.githubusercontent.com/qq253498229/docker-config-server-all-in-one/master/schema.sql[`schema.sql`]必须和 `docker-compose.yml` 放在同一目录) 可以一键创建配置中心后端以及依赖的数据库，并初始化数据库结构。

启动服务后即可访问 http://localhost 来管理配置中心了

== 配置中心后端

快速开始中使用的镜像，本质上就是提取前后端镜像中的业务代码，打包成一个新的镜像。 所以后端的配置同样可以套用到快速开始中。

后端采用 `SpringBoot 2.3.1.RELEASE`、 `SpringCloud Hoxton.SR5` 版本开发，数据库使用的是 `MySQL`，注册中心支持 `Eureka` 和 `Consul`。如果没有满足您的需求，可以在 <<contribution>> 中查看并提交issues或自行修改。

=== 后端支持参数

.后端支持参数
[%autowidth]
|===
| 参数名 | 默认值 | 说明

|SERVER_PORT
|8888
|后端暴露的端口

|MYSQL_HOST
|localhost
|数据库地址

|MYSQL_PORT
|3306
|数据库端口号

|MYSQL_DATABASE
|application_configuration
|数据库名

|MYSQL_USERNAME
|root
|数据库登录名

|MYSQL_PASSWORD
|root
|数据库登录密码

|APPLICATION_NAME
|config-server
|SpringBoot中的 `spring.application.name`

|DISCOVERY_TYPE
|url
|注册中心类型，`url/eureka/consul`，其中url为不使用注册中心

|CONSUL_TOKEN
|B595BC8E-DE44-4510-82D7-ECF5657F4D4D
|当 DISCOVERY_TYPE 为 `consul` 时生效，consul的 `acl_token`

|CONSUL_HOST
|8500
|当 DISCOVERY_TYPE 为 `consul` 时生效，consul的地址

|CONSUL_PORT
|8500
|当 DISCOVERY_TYPE 为 `consul` 时生效，consul的端口号

|EUREKA_SERVICE_URL
|http://admin:admin@localhost:8761/eureka/
|当 DISCOVERY_TYPE 为 `eureka` 时生效，eureka 的注册地址
|===

== 配置中心前端

前端使用了 https://angular.cn/[Angular 9] 、 https://ng.ant.design/[NG-ZORRO]， 以及 https://github.com/brtnshrdr/angular2-hotkeys#readme[angular2-hotkeys] 、 https://lodash.com/[lodash] 等。

=== 前端支持参数

.前端支持参数
[%autowidth]
|===
| 参数名 | 默认值 | 说明

|BACKEND_PATH
|http://config:8888
|Nginx中反向代理的后端地址
|===

NOTE: 注意这个参数在快速启动中不生效，因为前后端使用的是同一个容器，所以固定为 http://localhost:8888

== 源码地址

源码托管在 https://gitee.com/[Gitee] 中：

https://gitee.com/consolelog/codeforfun-config-server-frontend[Gitee-配置中心-前端]、
https://gitee.com/consolelog/codeforfun-config-server[Gitee-配置中心-后端]、
https://gitee.com/consolelog/docker-config-server-all-in-one[Gitee配置中心-快速启动]

同时也提供了 https://github.com/[Github] 地址作为备用：

https://github.com/qq253498229/codeforfun-config-frontend[Github-配置中心-前端]、
https://github.com/qq253498229/codeforfun-config-server[Github-配置中心-后端]、
https://github.com/qq253498229/docker-config-server-all-in-one[Gitee配置中心-快速启动]

== 开源协议

本项目遵循 MIT 协议，虽然我也不知道这个协议具体是啥意思，但是原则上你可以随便使用本项目，当然前提是不触犯法律: http://xingfa.org/[中华人民共和国刑法] 、 https://paperclip.feishu.cn/file/boxcnZGTyENVDRcBIRUlFtM0YVf[中华人民共和国民法典(草案)]。

== 更新日志

暂无

[[contribution]]
== 贡献指南

你可以在 https://gitee.com/consolelog/codeforfun-config-server-frontend/issues[前端] 、 https://gitee.com/consolelog/codeforfun-config-server/issues[后端] 以及 https://gitee.com/consolelog/docker-config-server-all-in-one/issues[快速启动] 的 issues 列表中提交 issue。

同时您也可以提供 PullRequest 贡献代码。